config/routes.rb
Rails.application.routes.draw do
    
  root to: "courses#index"
  resources :courses
  resources :lessons
  get '/courses/:id/lessons', to: 'courses#lessons'
  get 'about', to: 'pages#about'
  # get 'contact', to: 'pages#contact'
  get 'login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  after_validation :set_slug, only: [:create, :update]
  
  include PgSearch::Model
  pg_search_scope :search,
    against: { title: 'A', overview: 'B', objectives: 'C', notes: 'D' },
    using: { tsearch: { dictionary: 'english' } }
  
  has_many :lessons
  
  validates :title, presence: true, length: { maximum: 100 }
  validates :position, presence: true
  validates :duration, presence: true  
  validates :overview, presence: true
  validates :objectives, presence: true
  validates :notes, presence: true
  validates :color, presence: true
  
  def to_param
    "#{id}-#{slug}"
  end
  
  private

    def set_slug
      self.slug = title.to_s.parameterize
    end

end

app/models/lesson.rb
class Lesson < ApplicationRecord
  
  include PgSearch::Model
  pg_search_scope :search,
    against: %i[title],
    using: { tsearch: { dictionary: 'english' } }
  
  belongs_to :course
  
  validates :course_id, presence: true, numericality: { only_integer: true }
  validates :position, presence: true, numericality: { only_integer: true }
  validates :title, presence: true
  validates :url, presence: true
  validates :duration, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  
  private
  
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :lessons, :edit, :update, :destroy]
  before_action :logged_in_user, except: [:index, :show]

  # GET /courses
  # GET /courses.json
  def index
    unless params[:search]
      @title = "Learn to code for free"
      @courses = Course.order(position: :desc) 
    else
      @title = "Search | #{params[:search]}"
      courses = Course.search(params[:search])
      lessons = Lesson.search(params[:search])
      
      results = []
      lessons.each do |l|
        results << l.course
      end
      
      rows = results + courses
      
      @courses = rows.uniq      
    end
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @title = @course.title
    @lessons = @course.lessons
  end
  
  # GET /courses/1/lessons
  def lessons
    @lessons = @course.lessons
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:title, :position, :duration, :overview, :objectives, :notes, :color, :seek)
    end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user

  # GET /lessons
  # GET /lessons.json
  def index
    @lessons = Lesson.all
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show
  end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
  end

  # GET /lessons/1/edit
  def edit
  end

  # POST /lessons
  # POST /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to @lesson, notice: 'Lesson was successfully created.' }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1
  # PATCH/PUT /lessons/1.json
  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to @lesson, notice: 'Lesson was successfully updated.' }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to lessons_url, notice: 'Lesson was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lesson_params
      params.require(:lesson).permit(:position, :title, :url, :duration, :course_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about
    @title = "About Me"
  end
  
  def contact
    @title = "Contact Me"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end
  
  def create
    user = User.find_by(name: params[:session][:name].downcase)
    if user&.authenticate(params[:session][:password])
      log_in user
      redirect_to root_url
    else
      
      render :new
    end
  end
  
  def destroy
    log_out
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end
  
  # Returns the current logged-in user (if any).
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
  
  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/views/courses/_form.html.erb
<%= form_with(model: course, local: true, class: "row g-3 be-form") do |form| %>

  <%= render 'layouts/errors', object: @course %>

  <div class="field">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :position, class: "form-label" %> <br>
    <%= form.number_field :position, class: "form-control" %>
  </div>
  
  <div class="field">
    <%= form.label :duration, class: "form-label" %>
    <%= form.text_field :duration, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :overview, class: "form-label" %>
    <%= form.text_area :overview, rows: 7, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :objectives, class: "form-label" %>
    <%= form.text_area :objectives, rows: 7, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :notes, class: "form-label" %>
    <%= form.text_area :notes, rows: 7, class: "form-control" %>
  </div>
  
  <div class="field">
    <%= form.label :color, class: "form-label" %>
    <%= form.text_field :color, class: "form-control" %>
  </div>
  
  <div class="d-grid gap-2">
    <%= form.submit class: "btn btn-primary" %>
  </div>
  
<% end %>

app/views/courses/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-10 offset-lg-1">
      <h1><%= @course.title %></h1>
      <%= render 'form', course: @course %>
    </div>
  </div>
</div>

app/views/courses/index.html.erb
<% unless params[:search] %>
<div class="container d-none d-xl-block">
 
  <div>

    <div class="row">
      <div class="col-lg-12">
       
        <div class="row">
          <div class="col-lg-7">
         
<!--
            <div>
              <h1>
                Linux is for<br>
                <span id="spiel" class="pome"></span>
              </h1>                
            </div>
-->
            
            
            <div>
              <h1 class="headline fira-m tagline">
                Learn to code,
                <br>change your life               
              </h1>              
<!--              <p class='display-2'>Expertly curated screencasts for the modern professional</p>  -->
            </div>

         
          </div> <!-- col -->
          
          
          <div class="d-none d-lg-block col-lg-5">
            <%= image_tag("man-and-lady-on-laptop.webp",
              alt: "Man and lady on laptop", class: "img-fluid") %>
          </div>
        </div> <!-- row -->
        
      </div>
    </div> <!-- row -->

  </div>

</div>
<% end %>

<div id="courses">
     
  <div class="container">
      
    <div class="row">
    
      <div class="col-lg-12">
       
        <div class="row fira-m">
          <h1 style="margin-top: -50px;" class="display-5 fw-bold">
            <% unless params[:search] %>
              Catalog
            <% else %>
              <% if @courses.length == 0 %>
                No Results
              <% else %>
                Search Results
              <% end %>
            <% end %>
          </h1>
        </div>
        
        <div class="row" style="margin-top: 15px">
          
          <% @courses.each do |course| %>
          
          <!-- Track -->
          <div class="mb-5 col-lg-4 col-md-6">
          <%= link_to course do %>
            <div class="pt-3 px-3 fira-m cards" style="box-shadow: -5px 5px <%= course.color %>; border: 2px solid <%= course.color %>;">
              <div class="centre">
                <div class="row">
                  <div class="col-12">

                    <span class="card-type oxym">
                      <%= "#{course.lessons.count} videos" if course.lessons.count > 0 %>
                      <%= "Microdegree" unless course.lessons.count > 0 %>
                      <hr>
                    </span>

                    <div class="row">
                      <div class="col-md-11">
                        <h2> <%= course.title %> </h2>
                      </div>
                    </div>
                  </div> <!-- col-12 -->
                  
                  <div class="col-12">
                    <span> <%= course.duration %> </span>
                  </div>
                  
                  <div class="offset-10 col-2">
                    <% if course.lessons.count > 0 %>
                    <span class="material-icons-outlined">video_library</span>
                    <% else %>
                    <span class="material-icons-outlined school">school</span>
                    <% end %>
                  </div>

                </div> <!-- centre -->
              </div> <!-- centre -->
            </div> <!-- cards -->
          <% end %>
          </div> <!-- col-lg-4 -->         
          
          <% end %>
          
        </div>
      </div>
          
    </div> <!-- row -->
        
  </div> <!-- container -->
      
</div> <!-- courses -->

<!-- Rotate Banner Text -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    
<script>
  $(function () {
      var messages = [],
          index = 0;

      messages.push('Everyone!');
      messages.push('the System Architect');
      messages.push('the Network Admin');
      messages.push('the DevOps Engineer');

      function cycle() {
          $('#spiel').html(messages[index]);
          index++;

          if (index === messages.length) {
              index = 0;
          }

          setTimeout(cycle, 3000);
      }

      cycle();
  });
</script>

app/views/courses/lessons.html.erb
<div class="container-fluid">
  <div class="row">
     <div class="col-10 offset-1">
        <p id="notice"><%= notice %></p>

        <h1>
          <%= link_to @course do %>
            <%= sanitize @course.title %>
          <% end %>
          
          <%= link_to edit_course_path(@course) do %>
            <i class="ps-5 fas fa-pen-alt"></i>
          <% end %>
        </h1>

        <table class="table">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Lesson</th>
              <th scope="col" class="text-center">Len</th>              
              <th scope="col" colspan="2"></th>
            </tr>
          </thead>

          <tbody>
            <% @lessons.each do |lesson| %>
              <tr>
                <td><%= lesson.position %></td>
                
                <td><%= sanitize lesson.title %></td>
                
                <td class="text-center"><%= lesson.duration %></td>
                                
                <td>
                  <%= link_to edit_lesson_path(lesson) do %>
                    <i class="fas fa-pen-alt"></i>
                  <% end %>
                </td>
                
                <td>
                  <%= link_to lesson, method: :delete, data: { confirm: 'Are you sure?' } do %>
                    <i class="fas fa-dumpster"></i>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>

        <br>

        <%= link_to 'New Lesson', new_lesson_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/courses/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-10 offset-lg-1">
      <h1>New Course</h1>
      <%= render 'form', course: @course %>
    </div>
  </div>
</div>

app/views/courses/show.html.erb
<div class="container">
 
  <div>

    <div class="row">
     
      <!-- main col -->
      <div class="col-lg-12">
       
        <div class="row">
         
          <!-- left col -->
          <div class="col-lg-7 pull-up">
         
           <div>
              <h1 class="headline engle display-3"><%= @course.title %></h1>
              
              <div id="overview" class="jost"><%= sanitize @course.overview %></div>
              
              <div id="objectives">                
                <h2 class="engle">
                  <%= "What you'll learn" if @course.lessons.size > 0 %>
                  <%= "Learning Path" unless @course.lessons.size > 0 %>
                </h2>

                <div class="engle">
                  <%= sanitize @course.objectives %>
                </div> 
              </div>
              
              <% if @course.lessons.count > 0 %>
              <div id="lessons">
                <h2 class="engle mb-5 mt-2">Lessons</h2>
                
                <div class="row engle">
                  <% @lessons.each do |lesson| %>

                  <!-- lesson -->
                  <div class="col-12 <%= "lesson-container" unless lesson.position == 1 %> ">

                    <a href="" class="lesson" data-bs-toggle="modal" data-bs-target="#<%= "#{lesson.title.partition(" ").first}-#{lesson.position}" %>">
                      
                      <div class="row">
                        
                        <div class="col-1"> <%= lesson.position.to_s.rjust(2, '0') %>. </div>
                        <div class="col-9"> <%= sanitize lesson.title %> </div>

                        <div class="col-2">
                          <span class="duration">
                            <%= lesson.duration %>
                          </span>
                        </div>

                      </div> <!-- row -->
                      
                    </a>

                  </div>

                  <!-- lesson -->
                  
                  <!-- Modal -->
                  <div class="modal fade" id="<%= "#{lesson.title.partition(" ").first}-#{lesson.position}" %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog modal-xl odal-ialog-entered">
                     
                      <div class="modal-content">
                        
                        <div class="modal-body" style="background: #000">
                          <div class="ratio ratio-16x9">
                            <iframe modestbranding="1" src="<%= lesson.url %>" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                          </div>
                        </div>
                        
                        <div class="modal-footer">
                          <div class="container">
                            <div class="row">
                              <div class="col-lg-10"><%= sanitize lesson.title %></div>
                              <div class="col-lg-2">
                                <button style="padding: 10px 30px; font-size: 20px;" type="button" class="btn btn-danger" data-bs-dismiss="modal">
                                Close
                              </button>
                              </div>
                            </div>
                          </div>
                        </div>
                        
                      </div>
                      
                    </div>
                  </div>
                  <!-- Modal -->
                  
                  <% end %>
                </div>
                
              </div>
              <% end %>
              
            </div>

          </div>
          <!-- left col -->

          <!-- right col -->
          <div class="d-none d-lg-block col-lg-5">
           
            <div class="fira-m side-box" style="border: 2px solid <%= @course.color %>;
             box-shadow: 3px 1px 0px 2px <%= @course.color %>, 0px -1px 0px 2px <%= @course.color %>;">
            
              <%= sanitize @course.notes %>
              
              <% if logged_in? %>
                <hr>

                <ul class="fw-bold text-center ptserif">
                  <li>
                    <a href="/courses/<%= @course.id %>/lessons">
                      Manage this Course
                    </a>
                  </li>
                </ul>
              <% end %>
              
            </div>
            
          </div>
          <!-- right col -->
          
        </div> <!-- row -->
        
      </div>
      <!-- main col -->
      
    </div> <!-- row -->

  </div>

</div>

<!-- Stop video when Modal closes -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

<script>
  $(document).ready(function(){
      $('.modal').each(function(){
              var src = $(this).find('iframe').attr('src');
          $(this).on('click', function(){
              $(this).find('iframe').attr('src', '');
              $(this).find('iframe').attr('src', src);
          });
      });
  });
</script>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this course from being saved:</h2>

    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="container">
  <div id="footer">
    <div class="row">
      <div class="col-2 offset-5">
        <%= link_to root_path do %>
          <%= image_tag("logo.jpg",
              alt: "Red Car Zooming off", class: "img-fluid") %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
  <div class="mt-3 container-fluid">
    <a class="d-none d-lg-block navbar-brand three-d-btn cta bg" href="<%= root_path %>">AGABYTE</a>
    <div class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="me-5 navbar-toggler-icon"></span>
    </div>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="mt-5 navbar-nav me-auto mb-2 mb-lg-0">
        <li class="ms-5 ms-lg-3 nav-item">
          <a class="nav-link" aria-current="page" href="<%= root_path %>">Home</a>
        </li>
        <li class="ms-5 ms-lg-3 nav-item">
          <a class="nav-link" href="<%= about_url %>">About Me</a>
        </li>
        <li class="ms-5 ms-lg-3 nav-item">
          <!-- <a class="nav-link" href="<%#= contact_url %>">Contact Me</a> -->
          <a class="nav-link" href="https://www.linkedin.com/in/agabaphilip/" target="_blank">Contact Me</a>
        </li>
        <% if logged_in? %>
          <li class="ms-5 ms-lg-3 nav-item">
            <%= link_to "Logout", logout_path, method: :delete, class: "nav-link" %>
          </li>
        <% end %>
      </ul>      
      
      <%= form_tag courses_path, :method => "get", class: "mt-5 mb-2 ms-5 me-5", id: "search-form" do %>
        <label>

          <%= text_field_tag :search, params[:search], :required => true, :id => "nil" %>
          
          <ul>
            <li s>s</li><li e>e</li><li a>a</li><li r>r</li><li c>c</li><li h>h</li>
          </ul>
          
        </label>
        
      <% end %>
      
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Agabyte | <%= @title %></title>
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- Font Awesome 
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog==" crossorigin="anonymous" />
    -->
    
    <!-- Google Icons -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons|Material+Icons+Outlined">

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    
    <!-- Jost -->
    <link href="https://fonts.googleapis.com/css2?family=Jost&display=swap" rel="stylesheet">

    <!-- Englebert -->
    <link href="https://fonts.googleapis.com/css2?family=Englebert&display=swap" rel="stylesheet"> 
    
    <!-- Fira Mono -->
    <link href="https://fonts.googleapis.com/css2?family=Fira+Mono:wght@400;500&display=swap" rel="stylesheet">
    
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    
    <%= favicon_link_tag asset_path('favicon-lg.png') %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <%#= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
  
    <%= yield %>
    
    <%= render 'layouts/footer' %>
    
    <!-- Optional JavaScript -->
    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    
  </body>
</html>

app/views/lessons/_form.html.erb
<%= form_with(model: lesson, local: true, class: "row g-3 be-form") do |form| %>
    
  <%= render 'layouts/errors', object: @lesson %>

  <div class="field">
    <%= form.label :course_id, class: "form-label" %>
    <%= form.number_field :course_id, class: "form-control" %>
  </div>

     <div class="field">
    <%= form.label :position, class: "form-label" %>
    <%= form.number_field :position, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_area :title, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :url, class: "form-label" %>
    <%= form.text_area :url, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :duration, class: "form-label" %>
    <%= form.text_field :duration, class: "form-control" %>
  </div>

  <div class="d-grid gap-2">
    <%= form.submit class: "btn btn-primary btn-block" %>
  </div>
  
<% end %>

app/views/lessons/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-10 offset-lg-1">
      <h1><%= sanitize @lesson.title %></h1>
      <%= render 'form', lesson: @lesson %>
    </div>
  </div>
</div>

app/views/lessons/index.html.erb
<div class="container-fluid handlee">
  <div class="row">
     <div class="col-10 offset-1">
        <p id="notice"><%= notice %></p>

        <h1 class="display-4">All Lessons</h1>

        <table class="table fw-normal">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Title</th>
              <th scope="col" class="text-center">Len</th>
              <th scope="col" class="text-center">Course</th>
              <th scope="col" colspan="2"></th>
            </tr>
          </thead>

          <tbody>
            <% @lessons.each do |lesson| %>
              <tr>
                <td><%= lesson.id %></td>
                
                <td><%= sanitize lesson.title %></td>
                
                <td class="text-center"><%= lesson.duration %></td>
                <td class="text-center"><%= lesson.course_id %></td>
                                
                <td>
                  <%= link_to edit_lesson_path(lesson) do %>
                  <span class="material-icons-outlined pen">edit</span>
                  <% end %>
                </td>
                
                <td>
                  <%= link_to lesson, method: :delete, data: { confirm: 'Are you sure?' } do %>
                  <span class="material-icons-outlined trash">delete_forever</span>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>

        <br>

        <%= link_to 'New Lesson', new_lesson_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/lessons/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-10 offset-lg-1">
      <h1>New Lesson</h1>
      <%= render 'form', lesson: @lesson %>
    </div>
  </div>
</div>

app/views/lessons/show.html.erb
<div class="container" style="margin-top: -20px">

  <div class="row">
    
    <div class="col-6 offset-3 display-6">

      <p>
        <strong>Position:</strong>
        <%= @lesson.position %>
      </p>

      <p>
        <strong>Title:</strong>
        <%= @lesson.title %>
      </p>

      <p>
        <strong>Duration:</strong>
        <%= @lesson.duration %>
      </p>

      <p>
        <strong>Course:</strong>
        <%= @lesson.course_id %>
      </p>

      <%= link_to 'Edit Lesson', edit_lesson_path(@lesson) %> |
      <%= link_to 'View Course', @lesson.course %> |
      <%= link_to 'New Lesson', new_lesson_path %>

    </div>

  </div>

</div>

app/views/pages/contact.html.erb
<div class="container">
 
  <div>

    <div class="row">
      <div class="col-lg-10 offset-lg-1">
       
        <div class="row">
          
          <!-- left col -->
          <div class="col-lg-7">
         
            <div>
              <h1 class="headline text-center text-break fira-m pull-up display-4">
                philip@agabyte.com
              </h1>
            </div>
         
          </div>
          <!-- left col -->

          <!-- right col -->
          <div class="d-none d-lg-block col-lg-5">
            <%= image_tag("two-cars-backing-each-other.png",
              alt: "two cars backing each other", class: "img-fluid") %>
          </div>
          <!-- right col -->
          
        </div> <!-- row -->
        
      </div>
    </div> <!-- row -->

  </div>

</div>